### ISSUE TITLE
Track the Map Pan

### ISSUE THREAD

**Issue by michae1duncan** [michae1duncan/county-reporter#1]
Add/adjust functionality to track the map pan and only trigger the REST request when the map pan stops.

**Comment by travisbutcher** [comment]
The only way I have been getting this to work is to add a Timer object to track the updates and make it wait a second or two to determine when to trigger the search function.  I will be putting up a Pull Request to show how this could work.

**Comment by michae1duncan** [comment]
I was just looking at the Timer object today, but couldn't get it to work the way I was putting it in there.  Would like to see your example!

**Comment by michae1duncan** [comment]
Travis, Have you had a chance to do a pull request on your solution yet?
